repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        exclude: "(?x)^(\n  [^/]+|\n  modules/.*\n)$\n"
      - id: terraform_docs
        args:
        - --hook-config=--add-to-existing-file=false
        - --args=--config=.terraform-docs.yml
      - id: terraform_tflint
        args:
        - --args=--only=terraform_deprecated_interpolation
        - --args=--only=terraform_deprecated_index
        - --args=--only=terraform_unused_declarations
        - --args=--only=terraform_unused_required_providers
        - --args=--only=terraform_empty_list_equality
        - --args=--only=terraform_comment_syntax
        - --args=--only=terraform_documented_outputs
        - --args=--only=terraform_documented_variables
        - --args=--only=terraform_typed_variables
        - --args=--only=terraform_module_pinned_source
        - --args=--only=terraform_required_version
        - --args=--only=terraform_required_providers
        - --args=--only=terraform_workspace_remote
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.21.3
    hooks:
      - id: commitizen-branch
        stages:
        - post-commit
        - push
