formatter: markdown table
version: 0.17
recursive:
  enabled: false
content: |-
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Inputs }}  
  {{ .Outputs }}
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
